name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -e .[linters] --no-cache-dir
      - name: Run ruff format
        run: ruff format .
      - name: Run ruff check
        run: ruff check .
      - name: Run codespell
        run : codespell .

  tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -e . --no-cache-dir
      - name: Run tests
        run: python -m unittest
      - name: Check for uncommitted changes
        run: |
          git config --global core.safecrlf false
          git diff --exit-code || (echo "Untracked changes found" && exit 1)